/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_Project;

import arbolg.Arbolphsh;
import arbolg.Nodo;
import arbolg.WindowsFringes;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Iosvani
 */
public class DialogModal extends javax.swing.JDialog {

    private DefaultListModel model_in = new DefaultListModel();
    private DefaultListModel model_out = new DefaultListModel();

    ArrayList<String> in = new ArrayList<String>();
    private ArrayList<String> out = new ArrayList<String>();

    /**
     * Creates new form DialogModal
     */
    public DialogModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Wind_main_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_Wind = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_Wind_selected = new javax.swing.JList();
        btn_aceptar = new javax.swing.JButton();
        btn_Selected = new javax.swing.JButton();
        btn_all = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Wind_main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list_Wind.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_Wind);

        Wind_main_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 170));

        list_Wind_selected.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_Wind_selected);

        Wind_main_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 120, 170));

        btn_aceptar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        Wind_main_panel.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 80, -1));

        btn_Selected.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_Selected.setText(">>");
        btn_Selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SelectedActionPerformed(evt);
            }
        });
        Wind_main_panel.add(btn_Selected, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, -1));

        btn_all.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btn_all.setText("All");
        btn_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allActionPerformed(evt);
            }
        });
        Wind_main_panel.add(btn_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 60, -1));

        btn_delete.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_delete.setText("<<");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        Wind_main_panel.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 60, -1));

        getContentPane().add(Wind_main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SelectedActionPerformed
        // TODO add your handling code here:
        if (list_Wind.getSelectedIndices().length > 0) {
            int index = list_Wind.getSelectedIndices().length - 1;
            while (list_Wind.getSelectedIndices().length != 0) {
                model_out.addElement(model_in.getElementAt(list_Wind.getSelectedIndices()[index]));
                model_in.remove(list_Wind.getSelectedIndices()[index--]);
            }
            list_Wind.setModel(model_in);
            list_Wind_selected.setModel(model_out);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione alguna Ventana!!!", "INFORMACIÓN", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_SelectedActionPerformed

    private void btn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allActionPerformed
        // TODO add your handling code here:
        while (model_in.size() != 0) {
            model_out.addElement(model_in.getElementAt(0));
            model_in.remove(0);
        }
        list_Wind.setModel(model_in);
        list_Wind_selected.setModel(model_out);
    }//GEN-LAST:event_btn_allActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (list_Wind_selected.getSelectedIndices().length > 0) {
            int index = list_Wind_selected.getSelectedIndices().length - 1;
            while (list_Wind_selected.getSelectedIndices().length != 0) {
                model_in.addElement(model_out.getElementAt(list_Wind_selected.getSelectedIndices()[index]));
                model_out.remove(list_Wind_selected.getSelectedIndices()[index--]);
            }
            list_Wind.setModel(model_in);
            list_Wind_selected.setModel(model_out);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione alguna Ventana!!!", "INFORMACIÓN", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        out = new ArrayList<>();
        for (int i = 0; i < model_out.size(); i++) {
            getOut().add((String)model_out.getElementAt(i));
        }
        dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

     /**
     * RECORRER EL ARBOL EN POSTORDEN*
     */
    public void postOrden_Fill_List(Arbolphsh<WindowsFringes> tree) {
        postOrdenR_Fill_List(tree.getRaiz());
    }

    private void postOrdenR_Fill_List(Nodo<WindowsFringes> nodo) {
        if (nodo != null) {
            Nodo<WindowsFringes> ph = nodo.getPH();
            postOrdenR_Fill_List(ph);
            while (ph != null) {
                ph = ph.getSH();
                postOrdenR_Fill_List(ph);
            }
            // PREGUNTO SI EL NODO ES HOJA Y SI SI LLAMO AL ALGORITMO DE RS
            if (nodo.getPH() == null) {
                // Anhado un elemento al List
                String nameWind = nodo.getInfo().getName();
                model_in.addElement(nameWind);
                list_Wind.setModel(model_in);
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModal dialog = new DialogModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Wind_main_panel;
    private javax.swing.JButton btn_Selected;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_all;
    private javax.swing.JButton btn_delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList list_Wind;
    private javax.swing.JList list_Wind_selected;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the out
     */
    public ArrayList<String> getOut() {
        return out;
    }
}
